spring:
  profiles:
    active: relese
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.196.194.14:3306/springboot
    username: root
    password: lytech
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
